config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'books#top'
  resources :books

  #post'books'=>'books#create'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	validates :title, presence: true
	validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def top
  end

  def index
  	@books = Book.all
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
  end

  def create
    @books = Book.all
    @book = Book.new(book_params)
    if
    @book.save
    redirect_to book_path(@book.id), flash:{success: "Book was successfully created."}
    else
    render :index
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    @book.update(book_params)
    if
    @book.save
    redirect_to book_path(@book.id), flash:{success: "Book was successfully created."}
    else
    render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end


  private

  def book_params
  	params.require(:book).permit(:title,:body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div class="error">
      <ul>
        <% @book.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

    <h4>Title</h4>
    <%= f.text_field :title %>
    <h4>body</h4>
    <%= f.text_area :body %>
    <br>
    <%= f.submit 'Update Book' %>
<% end %>

<%= link_to"show", book_path(@book.id)%>
<%= link_to"back", books_path %>

app/views/books/index.html.erb
<body>

  <h1>Books</h1>
  <table border="0" cellpadding="8" cellspacing="10">
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th> </th>
    </tr>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.body %></td>
        <td><%= link_to"show", book_path(book.id)%></td>
        <td><%= link_to"edit", edit_book_path(book.id)%></td>
        <td><%= link_to"destroy", book_path(book), method: :delete, data: { confirm: "Are you sure?", commit:"Ok", cancel:"キャンセル"} %></td>
       </tr>
    <% end %>
  </table>
  <br>
  <br>
  <br>


  <h2>New book</h2>
  <%= form_for(@book) do |f| %>
    <div class="error">
     <% if @book.errors.any? %>
      <ul>
        <% @book.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
     <% end %>
    </div>


  <h4>Title</h4>
   <%= f.text_field :title %>
  <h4>Body</h4>
   <%= f.text_area :body %>
   <%= f.submit 'Create book' %>
   <% end %>

</body>

app/views/books/show.html.erb
<%= flash[:success]%>

<h2>Title:</h2>
<p><%= @book.title %></p>
<h2>Body:</h2>
<p><%= @book.body %></p>

<%= link_to"edit", edit_book_path(@book.id)%>
<%= link_to"back", books_path %>

app/views/books/top.html.erb
<h1>ようこそBookersへ！</h1>

 <p>Bookersでは、さまざまな書籍に関するあなたの意見や</p>
 <p>印象を共有し交換することができます</p>

 <p><%= link_to"start", books_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>